# site settings
title: Openphone Insights Squad
subtitle: Data-driven insights for better business communication
email: jgrouleau@gmail.com
description: I'm the perfect candidate to lead OpenPhone's Insights Squad, as the new Senior Engineering Manager. This site presents a strategic vision for how OpenPhone can empower its customers to derive valuable insights from their communication data. By leveraging AI and intuitive analytics tools, we can transform raw interactions into actionable intelligence, helping businesses understand their customers better, optimize their communication strategies, and drive growth.
baseurl: "/openphone-insight-squad"
url: "https://jgrouleau.github.io"
author:
  name: Jean-Guy Rouleau
  email: jgrouleau@gmail.com

phone: +1 (705) 707-1441
city: North Bay
state: "ON"
country: Canada

# homepage tiles
tiles-source: pages
tiles-count: 8

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty

socials:
  WordPress: https://jean-guy.rouleau.website
  GitHub: https://github.com/jgrouleau
  LinkedIn: https://www.linkedin.com/in/jgrouleau/

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
