# site settings
title: Openphone Insights Squad
subtitle: Data-driven insights for better business communication
email: insights@openphone.co
description: A collection of data-driven insights and analysis for business communication and phone system optimization.
baseurl: "/openphone-insight-squad"
url: "https://jgrouleau.github.io"
author:
  name: Jean-Guy Rouleau
  email: jgrouleau@gmail.com
  phone: (705) 707-1441
  city: North Bay
  state: ON
  country: Canada

# homepage tiles
tiles-source: pages
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  WordPress: https://jean-guy.rouleau.website
  GitHub: https://github.com/jgrouleau/openphone-insight-squad
  LinkedIn: https://www.linkedin.com/in/jgrouleau/

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
