# site settings
title: Openphone Insights Squad
subtitle: Data-driven insights for better business communication
email: insights@openphone.co
description: A collection of data-driven insights and analysis for business communication and phone system optimization.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jgrouleau.github.io/openphone-insight-squad" # the base hostname & protocol for your site
author:
  name: Openphone Insights Team
  email: insights@openphone.co

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/jgrouleau/openphone-insight-squad

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
